#ifndef GENERIC_ERRORS_H
#define GENERIC_ERRORS_H

typedef enum
{
    FUNCTION_SUCCESS,
    GENERIC_FAILURE,
    NOT_YET_IMPLEMENTED,
    INVALID_INPUT_ERROR,
    MEMORY_ALLOCATION_FAILURE
} dsa_err_t;

#endif
