#ifndef GENERIC_ERRORS_H
#define GENERIC_ERRORS_H

typedef enum
{
    FUNCTION_SUCCESS,
    GENERIC_FAILURE,
    NOT_YET_IMPLEMENTED,
    NULL_INPUT_ERROR,
    MEMORY_ALLOCATION_FAILURE
} structure_status_t;

#endif
